jobs:
  rust-build-arm:
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          target: mips64el-unknown-linux-gnuabi64
          override: true
#      - name: Set up Docker
#        uses: docker/setup-docker-action@v4
      - name: Build
        run: |
          apt-get update -y && apt-get install -y upx;
          cargo build --release --target mips64el-unknown-linux-gnuabi64
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust-app-arm
          path: target/mips64el-unknown-linux-gnuabi64/release/lx-music-song-scraper
on:
  push:
    branches:
      - main