env:
  CARGO_TERM_COLOR: always

jobs:
  rust-build-mipsel:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - target: mips-unknown-linux-gnu
            toolchain: nightly
          - target: mipsel-unknown-linux-gnu
            toolchain: nightly
          - target: mips64el-unknown-linux-gnuabi64
            toolchain: nightly
          - target: mipsel-unknown-linux-musl
            toolchain: nightly
          - target: mips64-unknown-linux-gnuabi64
            toolchain: nightly

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: |
          rustup set profile minimal
          rustup toolchain install ${{ matrix.platform.toolchain }}
          rustup default ${{ matrix.platform.toolchain }}
          rustup override set ${{ matrix.platform.toolchain }}
          cargo install cross
#      - name: Set up Docker
#        uses: docker/setup-docker-action@v4
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: .
          cache-all-crates: true
          cache-on-failure: true
      - name: Build
        run: |
          apt-get update -y && apt-get install -y upx;
          cross build --release --target ${{ matrix.platform.target }} -Z build-std=std,panic_abort,proc_macro,core
#          upx target/${{ matrix.platform.target }}/release/lx-music-song-scraper
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.target }}
          path: target/${{ matrix.platform.target }}/release/lx-music-song-scraper
  rust-build-arm:
    strategy:
      fail-fast: false
      matrix:
        platform:
#          - target: aarch64-unknown-linux-gnu
#            toolchain: stable
          - target: aarch64-unknown-linux-musl
            toolchain: stable
#          - target: arm-unknown-linux-gnueabi
#            toolchain: stable
          - target: armv7-unknown-linux-gnueabi
            toolchain: stable
          - target: arm-unknown-linux-musleabi
            toolchain: stable
          - target: armv7-unknown-linux-musleabi
            toolchain: stable
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Install Rust
          run: |
            rustup set profile minimal
            rustup toolchain install ${{ matrix.platform.toolchain }}
            rustup default ${{ matrix.platform.toolchain }}
            rustup override set ${{ matrix.platform.toolchain }}
            cargo install cross
      #      - name: Set up Docker
      #        uses: docker/setup-docker-action@v4
        - name: Rust Cache
          uses: Swatinem/rust-cache@v2
          with:
            workspaces: .
            cache-all-crates: true
            cache-on-failure: true
        - name: Build
          run: |
            cross build --target ${{ matrix.platform.target }} --release
    #          upx target/${{ matrix.platform.target }}/release/lx-music-song-scraper
        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: ${{ matrix.platform.target }}
            path: target/${{ matrix.platform.target }}/release/lx-music-song-scraper
on:
  push:
    branches:
      - main