jobs:
  rust-build-arm:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - target: x86_64-unknown-linux-musl
            toolchain: stable
          - target: aarch64-unknown-linux-musl
            toolchain: stable
          - target: mips-unknown-linux-gnu
            toolchain: nightly
          - target: mipsel-unknown-linux-gnu
            toolchain: nightly
          - target: mips64el-unknown-linux-gnuabi64
            toolchain: nightly

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: |
          rustup set profile minimal
          rustup toolchain install ${{ matrix.platform.toolchain }}
          rustup default ${{ matrix.platform.toolchain }}
          rustup override set ${{ matrix.platform.toolchain }}
          cargo install cross
#      - name: Set up Docker
#        uses: docker/setup-docker-action@v4
      - name: Build
        run: |
          apt-get update -y && apt-get install -y upx;
          cross build --release --target mips-unknown-linux-gnu --features full
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust-app-arm
          path: target/mips-unknown-linux-gnu/release/lx-music-song-scraper
on:
  push:
    branches:
      - main