jobs:
  rust-build-arm:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: armv7-unknown-linux-gnueabi
          override: true
#      - name: Set up Docker
#        uses: docker/setup-docker-action@v4
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target armv7-unknown-linux-gnueabi --release
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust-app-arm
          path: target/armv7-unknown-linux-gnueabi/release/lx-music-song-scraper
on:
  push:
    branches:
      - main